#%RAML 1.0
title: Group API
version: 1.0

/test:
  get:
    description: Get test data
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "key": "SomeKey",
                "value": "someValue"
              }