#%RAML 1.0
title: Sample API

/test:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "key": "SomeKey",
                "value": "SomeValue
              }