#%RAML 1.0
title: Group API
version: 1.0
types:
  testModel: !include model/testModel.json

/test:
  get:
    description: Get test data
    responses:
      200:
        body:
          application/json:
            type: testModel