name: Increment project versions based on release

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEVOPS_TOKEN }}

      - name: Get version from release if valid
        id: get_version
        run: |
          if [[ ${{ github.ref }} =~ refs\/tags\/[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
          else
            exit 1
          fi

      - name: Set up git user
        run: |
          git config user.name alfamedevops
          git config user.email alfamedevops@alfame.com

      - name: Set project version to release version and commit
        run: |
          mvn -B versions:set -DnewVersion=$VERSION versions:commit
          mvn -f ./mule-bpm-module/pom.xml -B versions:set -DnewVersion=$VERSION versions:commit
          git add "**/pom.xml"
          git commit -m "Automated release commit"
          git push origin HEAD:master

      - name: Set project version to next snapshot version and commit
        run: |
          mvn -B versions:set -DnextSnapshot=true versions:commit
          mvn -f ./mule-bpm-module/pom.xml -B versions:set -DnextSnapshot=true versions:commit
          git add "**/pom.xml"
          git commit -m "Automated snapshot commit"
          git push origin HEAD:master

      - name: Merge changes to develop
        run: |
          git checkout develop
          git merge master --commit --no-edit
          git push origin HEAD:develop
